.TH "org.firstinspires.ftc.teamcode.SuperSecretTelemetry" 3 "Sun Mar 28 2021" "Tech Tigers FTC Program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.firstinspires.ftc.teamcode.SuperSecretTelemetry
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBaddTelemetry\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBlettersVisible\fP = 4"
.br
.ti -1c
.RI "static int \fBlettersPosition\fP = 0"
.br
.ti -1c
.RI "static String[][] \fBletters\fP"
.br
.ti -1c
.RI "static String[][] \fBlines\fP"
.br
.ti -1c
.RI "static int \fBk\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tech Tigers FTC Program from the source code\&.
