.TH "org.firstinspires.ftc.teamcode.techTigerAuto" 3 "Sun Mar 28 2021" "Tech Tigers FTC Program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.firstinspires.ftc.teamcode.techTigerAuto
.SH SYNOPSIS
.br
.PP
.PP
Inherits LinearOpMode\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrunOpMode\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void org\&.firstinspires\&.ftc\&.teamcode\&.techTigerAuto\&.runOpMode ()"
Entrance point of the program 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tech Tigers FTC Program from the source code\&.
