.TH "org.firstinspires.ftc.teamcode.ArmServos" 3 "Sun Mar 28 2021" "Tech Tigers FTC Program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.firstinspires.ftc.teamcode.ArmServos
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetup\fP ()"
.br
.ti -1c
.RI "static void \fBsetArcPosition\fP (double position)"
.br
.ti -1c
.RI "static void \fBsetArcPosition\fP (double position, boolean disableServoOffset)"
.br
.ti -1c
.RI "static void \fBsetWobbleHolderPosition\fP (double position)"
.br
.ti -1c
.RI "static void \fBaddToWobbleHolderServos\fP (double increment)"
.br
.ti -1c
.RI "static void \fBaddToArcServos\fP (double increment)"
.br
.ti -1c
.RI "static void \fBaddTelemetry\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static double \fBhigh\fP = 0\&.76"
.br
.ti -1c
.RI "static double \fBmid\fP = 0\&.3"
.br
.ti -1c
.RI "static double \fBlow\fP = 0\&.104"
.br
.ti -1c
.RI "static double \fBservoOffset\fP = 0\&.120"
.br
.ti -1c
.RI "static double \fBinternalServoOffset\fP = 0\&.0175"
.br
.ti -1c
.RI "static Servo \fBsLeftArm\fP"
.br
.ti -1c
.RI "static Servo \fBsRightArm\fP"
.br
.ti -1c
.RI "static Servo \fBsWobbleHolder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A servo helper class, for the ARM 
.br
 NOTE: Generally this class should not need changes, other than the first 5 variables 
.SH "Member Function Documentation"
.PP 
.SS "static void org\&.firstinspires\&.ftc\&.teamcode\&.ArmServos\&.addTelemetry ()\fC [static]\fP"
Adds servo telemetry data 
.br
 NOTE: This does not update telemetry 
.SS "static void org\&.firstinspires\&.ftc\&.teamcode\&.ArmServos\&.addToArcServos (double increment)\fC [static]\fP"
Increments the arc servos 
.PP
\fBParameters\fP
.RS 4
\fIincrement\fP The amount to increment the servos by 
.br
 NOTE: For debugging purposes ONLY! 
.RE
.PP

.SS "static void org\&.firstinspires\&.ftc\&.teamcode\&.ArmServos\&.addToWobbleHolderServos (double increment)\fC [static]\fP"
Increments the wobble holder servo 
.PP
\fBParameters\fP
.RS 4
\fIincrement\fP The amount to increment the servo by 
.br
 NOTE: For debugging purposes ONLY! 
.RE
.PP

.SS "static void org\&.firstinspires\&.ftc\&.teamcode\&.ArmServos\&.setArcPosition (double position)\fC [static]\fP"
Sets the position of the arc servos 
.br
 NOTE: The function will not prevent you from nullifing the internalServoOffset at extreme ranges 
.PP
\fBParameters\fP
.RS 4
\fIposition\fP The position to go to 
.RE
.PP

.SS "static void org\&.firstinspires\&.ftc\&.teamcode\&.ArmServos\&.setArcPosition (double position, boolean disableServoOffset)\fC [static]\fP"
Sets the position of the arc servos 
.br
 NOTE: The function will not prevent you from nullifing the internalServoOffset at extreme ranges 
.PP
\fBParameters\fP
.RS 4
\fIposition\fP The position to go to 
.br
\fIdisableServoOffset\fP When true servoOffset is not added to the position 
.RE
.PP

.SS "static void org\&.firstinspires\&.ftc\&.teamcode\&.ArmServos\&.setup ()\fC [static]\fP"
Sets up the servos 
.br
 NOTE: This must be called before any other functions 
.SS "static void org\&.firstinspires\&.ftc\&.teamcode\&.ArmServos\&.setWobbleHolderPosition (double position)\fC [static]\fP"
Sets the position of the wobble holder servo 
.PP
\fBParameters\fP
.RS 4
\fIposition\fP The position to go to 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Tech Tigers FTC Program from the source code\&.
